version: "3"
services:
  chatgpt-discord-bot:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/DiscordBot
    env_file:
      - dev.env
  redis:
    image: redis:7.0.7-alpine
